### ISSUE TITLE
Can not dye a pack on a multiplayer server.

### ISSUE THREAD

**Issue by AdaraChristine** [gr8pefish/IronBackpacks#245]
#### Issue Description:
Cant dye packs on a multiplayer server. Works in single player.

#### What happens:
No output appears, thus pack does not get dyed.
![2018-06-21_15 24 52](https://user-images.githubusercontent.com/30163566/41748607-6f8cbca8-7567-11e8-9c7e-168f00003b9f.png)

#### What you expected to happen:
Pack becomes dyed

#### Steps to reproduce (important):

1. Place pack in crafting table
2. place dye next to it
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: IronBackpacks-1.12.2-3.0.8-12
- Minecraft: 1.12.2
- Forge: 14.23.3.2697
Pack: Mystical Village 2

[15:09:26] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: 
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: 
	at gr8pefish.ironbackpacks.core.recipe.ColorBackpackRecipe.getDyeColor(ColorBackpackRecipe.java:57) ~[ColorBackpackRecipe.class:1.12.2-3.0.8-12]
	at gr8pefish.ironbackpacks.core.recipe.ColorBackpackRecipe.func_77572_b(ColorBackpackRecipe.java:40) ~[ColorBackpackRecipe.class:1.12.2-3.0.8-12]
	at net.minecraft.inventory.Container.func_192389_a(Container.java:798) ~[afr.class:?]
	at net.minecraft.inventory.ContainerWorkbench.func_75130_a(SourceFile:51) ~[afz.class:?]
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:93) ~[afy.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70) ~[agr.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281) ~[afr.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1158) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]

**Comment by AdaraChristine** [comment]
Do you need anything else from me about this bug?

**Comment by gr8pefish** [comment]
Sorry, I've been really busy and haven't been able to mod. When I get time to mod again I'll check this out and may have questions.

**Comment by AdaraChristine** [comment]
No worries! Thanks :)

**Comment by Elvarion** [comment]
Ill chip in on this
If you use a Tinker Crafting Table the Dye used will be duped
- IronBackpacks-1.12.2-3.0.8-12
- TConstruct-1.12.2-2.10.1.87
- forge-1.12.2-14.23.4.2715-universal

**Comment by TehNut** [comment]
The problem is the same as https://github.com/WayofTime/BloodMagic/pull/1250

Fairly simple fix as well https://github.com/WayofTime/BloodMagic/commit/924dc7b38d54c013d08d676ea2503f1fa8dffc5e
