### ISSUE TITLE
GUI issues, and crashing on NEI sort

### ISSUE THREAD

**Issue by Macropyre** [gr8pefish/IronBackpacks#41]
http://puu.sh/mo843/727fbe9c99.jpg

Forge 10.13.4.1558, Minecraft 1.7.10

Sorting causes player character to get booted out with an exception.

Errorlog tidbit:
[09:58:13] [Client thread/INFO]: [CHAT] Given [Diamond Backpack] \* 1 to <PROFILE NAME>
[09:58:15] [Client thread/WARN]: Failed to load texture: ironbackpacks:textures/guis/backpacks/12RowsOf11.png
java.io.FileNotFoundException: ironbackpacks:textures/guis/backpacks/12RowsOf11.png
    at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:67) ~[brg.class:?]
    at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:29) ~[bpu.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89) [bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:45) [bqf.class:?]
    at main.ironbackpacks.client.gui.inventory.GUIBackpack.func_146976_a(GUIBackpack.java:172) [GUIBackpack.class:1.7.10-1.2.12]
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78) [bex.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) [blt.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

Seems that the install is missing textures?
Just don't know about why it autosorts.

Quick update: Backpacks (Noticeably gold and diamond) "automatically sort" themselves, opening inventory reverts back to original item layout in inventory; taking an item from an automatically-sorted backpack causes an internal server error.

Any advice would be appreciated.

Thanks.

**Comment by gr8pefish** [comment]
On the texture issue: My guess is you have an invalid config value on the number of rows of the backpack(s). Check that it doesn't exceed 7 (i.e. 12 is too large).

Can you elaborate on the automatically sorting themselves? What is happening exactly? Do you have any upgrades on the backpack?

**Comment by Macropyre** [comment]
Zero upgrades. I brought my configs to default values by deleting the config file and rerunning the client again. No change.

I insert X item into, let's say, slot 5, it automatically goes to slot 0, for some odd reason.

I open it again and it's at slot 5. I insert another item, and that item goes to slot 0, and the previous goes to slot 1.

**Comment by gr8pefish** [comment]
Hmm, sounds like some form of server de-sync error. Was this always happening? Can you think of something that may have caused this? Are the server and client configs the same?

It really seems like a config issue for the texture, I will test myself if deleting it and restarting causes any errors. **Edit:** I cannot duplicate the missing texture issue even with regeneration the config, manually check your config(s) are okay.

**Comment by Macropyre** [comment]
Did a server reboot, with fresh installs of the recent version of Iron Backpacks.

It's working properly now, but I haven't fiddled with any other config or added/removed any mods. 

Certainly very odd. Sorry for the trouble I suppose...?

**Comment by gr8pefish** [comment]
Very strange, glad you go it to work okay now though! If anything else pops up, I'll be here. Sorry I couldn't help you with that last issue as well, like I said, strange bug ;)
