### ISSUE TITLE
Crash using new 2.0 version when equiping backpack

### ISSUE THREAD

**Issue by DarcClan** [gr8pefish/IronBackpacks#47]
Description: Exception in server tick loop

java.lang.NoSuchFieldError: worldObj
    at gr8pefish.ironbackpacks.util.helpers.IronBackpacksHelper.spawnEntityBackpack(IronBackpacksHelper.java:217)
    at gr8pefish.ironbackpacks.events.ForgeEventHandler.onPlayerLogIn(ForgeEventHandler.java:127)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_155_ForgeEventHandler_onPlayerLogIn_PlayerLoggedInEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:555)
    at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:175)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:239)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:54)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:190)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:289)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:189)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:250)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)

**Comment by Ioandar** [comment]
same, unable to load world after equip crash

this what I get when I try to load the world after crash -> http://pastebin.com/kpvsbPzP

Forge1723

**Comment by NerdMcBoon** [comment]
I don't know if it's the same issue, but my game completely stopped responding after I tried to open my backpack for the first time via right click.

I did not change anything in the config except turning the render off in first person mode.

As the game didn't really crash, there is no crash report, so I'll attach the log file instead

[IronBackpacksFreeze.txt](https://github.com/gr8pefish/IronBackpacks/files/106612/IronBackpacksFreeze.txt)
.
I'm still on Forge 1.8.9 - 11.15.0.1718, if that makes any difference.

**Comment by gr8pefish** [comment]
@DarcClan, @Ioandar: Are you both using Java 8? Are you both updating from an old world or is this a new one? I only ask because while I found issues with my entity backpacks, they aren't the exact same as yours. I may fix your issue indirectly, but right now it wouldn't be a specific fix for your issue since I cannot replicate it.

@NerdMcBoon Pretty sure that is a different issue, but I will try and fix both for the next release, as I expect/hope yours to be a simple fix. If it isn't I'll move it to another issue.

**Comment by Ioandar** [comment]
@gr8pefish Java 8 and updating from old world that used 'IronBackpacks-1.8-1.0.7'. 
- Having empty IronBackpack from old version in players inventory, 
- then crafting basic bachpack (chest with leather)
- pressing hotkey to equip -> crash

will test new world and report...
- java 8
- new world
- cheat in normal backpack
- hotkey, crash -> http://pastebin.com/gy1THiGz

Maybe related -> had Firewall warning together with this test

**Comment by gr8pefish** [comment]
Right, I'll look into it and try to figure this out and fix it.

**Comment by Ioandar** [comment]
tyvm, your backpacks are awesome!

**Comment by TehNut** [comment]
For some reason (let's just blame Mojang), _most_ methods and fields got obfuscated during the build but _some_ didn't. 

Edit:

Here is an example of what I mean: 

Left is broken, right is fixed

![Example](http://i.imgur.com/9j0o3tB.png)

**Comment by gr8pefish** [comment]
Fixed as of 2.0.2
