### ISSUE TITLE
Item dupe bug in latest version

### ISSUE THREAD

**Issue by rigerc** [gr8pefish/IronBackpacks#99]
#### Issue Description:
When I break a item I placed I get a duplicate back. The log gives this Iron Backpacks related error:

`[13:10:23] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$PlaceEvent@7987ff5:
java.lang.NoSuchMethodError: net.minecraftforge.event.world.BlockEvent$PlaceEvent.getHand()Lnet/minecraft/util/EnumHand;
	at gr8pefish.ironbackpacks.events.ForgeEventHandler.onBlockPlacedEvent(ForgeEventHandler.java:223) ~[ForgeEventHandler.class:1.10.2-2.2.12]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_984_ForgeEventHandler_onBlockPlacedEvent_PlaceEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:128) [ForgeEventFactory.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:802) [ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:144) [adz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:493) [lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) [me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [jj.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[13:10:23] [Server thread/ERROR] [FML/]: Index: 3 Listeners:
[13:10:23] [Server thread/ERROR] [FML/]: 0: NORMAL
[13:10:23] [Server thread/ERROR] [FML/]: 1: ASM: biomesoplenty.common.handler.AchievementEventHandler@3bea6f59 onBlockPlaced(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
[13:10:23] [Server thread/ERROR] [FML/]: 2: ASM: de.maxhenkel.gravestone.Events@691b3ee onBlockPlace(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
[13:10:23] [Server thread/ERROR] [FML/]: 3: ASM: gr8pefish.ironbackpacks.events.ForgeEventHandler@40183204 onBlockPlacedEvent(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
[13:10:23] [Server thread/ERROR] [FML/]: 4: LOWEST
[13:10:23] [Server thread/ERROR] [FML/]: 5: ASM: org.winterblade.minecraft.harmony.utility.EventHandler@4a2fe18e onBlockPlaced(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
[13:10:23] [Server thread/ERROR] [FML/]: 6: ASM: blusunrize.immersiveengineering.common.EventHandler@7c703082 onBlockPlaced(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V`

#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 2.2.12
- Minecraft: 1.10
- Forge: 2116

**Comment by MineAnPlay** [comment]
Try with forge 12.18.2.2120 (dependencies were updated). (I would try it but I'm waiting for some mods to be compatible with forge 2116 and later). If that doesn't fix it then we will have to wait for gr8pefish. Also gr8pefish could you make the game not load if it requires a mod or later version because that will be helpful for all of us :).

**Comment by gr8pefish** [comment]
Oh yeah sorry, forgot to make the game load after that version of Forge. I believe this bug is only popping up because you are using the new version of IB with an old version of Forge. To fix it, downgrade to 2.2.11 for now, or update forge to 2120+.

**Comment by rigerc** [comment]
Upgrading Forge versions fixed it

**Comment by gr8pefish** [comment]
Alright cool. I'll still push out a version that explicitly warns others of this (in case they didn't read the changelog).
